### ISSUE TITLE
frida.core.RPCException: Error: access violation accessing 0x89 while running on an iPhone 7 iOS 13.5.1

### ISSUE THREAD

**Issue by xyn** [seemoo-lab/toothpicker#3]
I'm trying to run toothpicker on my iPhone 7 running iOS 13.5.1, I used "symbols_ios_13_5". I'm assuming the symbols are the issue as maybe 13.5 symbols aren't compatible with 13.5.1. How would I go about extracting the symbols from 13.5.1?

**Comment by jiska2342** [comment]
Dear @xyn,

indeed, the symbols change in every iOS version, no matter if minor or major, since all daemons get recompiled. Moreover, there are different versions depending on the architecture, i.e., the the `bluetoothd` on pe-A12 has different symbols than on A12+.

@nezza is currently working on *ToothPicker* :) He diffed the symbols for iOS 14.3 on an iPhone 7/8/X. Note that the symbols as pasted here are **unconfirmed**, so not sure if they work or not. 
```
// iOS 14.3, A11
    symbols_ios_14_3_iphonex: {
        allocateACLConnection: 0xed3a0,
        allocateLEConnection: 0xed74c,
        OI_SignalMan_Recv: 0x136828,
        OI_L2CAP_Recv: 0x12da74,
        bt_forceDisconnect: 0xd23d8,
        ACL_reception_handler: 0xf2b8c,
        OI_HCI_ReleaseConnection: 0xed9e0,
        create_connection: 0x147630,
        _GATT_LE_DisconnectedCB: 0x140568,
        ReadRemoteVersionInformationCB: 0x14d6cc,
        hci_handle_exists: 0xecffc,
        LE_ReadRemoteVersionInformationComplete: 0x148744,
        OI_LP_ConnectionAdded: 0x119c8c,
        btstack_free: 0x79f28,
        startSecurityPolicyEnforcement: 0x181334,
        enforceLinkPolicy: 0x181a34,
        registerTimeout: 0x17f51c,
        ble_adv_stuff: 0x441888,
        coreDumpPacketCounter: 0x31a800,
        OI_L2CAP_WriteMBUF: 0x115988,
        is_internal_build: 0x78b7c,
    },
```

He used the Ghida versioning tool. I prefer BinDiff for IDA Pro. Either way, the workflow is to import an older `bluetoothd` version extracted from an IPSW file and then diff it against your current version.

Instead of getting *ToothPicker* running on iOS 13.5.1, I would recommend upgrading your iPhone 7 (if it is a 7 and not a newer model) to iOS 14.3.

**Comment by xyn** [comment]
Using these addresses I'm getting the following error "frida.core.RPCException: Error: abort was called"
This is the whole crash log: https://paste.ubuntu.com/p/MzqWXFmycy/

**Comment by jiska2342** [comment]
Looks like some issue with the script or symbols again. Which iOS and Frida version are you running?

**Comment by xyn** [comment]
I am running iOS 14.3, iPhone 7 and the latest version of Frida installed from http://build.frida.re(I installed Frida for Pre A12 devices)

**Comment by xyn** [comment]
(I had restored from 13.5.1 to 14.3)

**Comment by SpiralBL0CK** [comment]
@jiska2342 any fix to xyn's issue ?

**Comment by ttdennis** [comment]
I will look into the issue this weekend, haven't had the chance to upgrade to 14.3 yet.

**Comment by ttdennis** [comment]
It seems to work for me. I'm using an iPhone 7 on iOS 14.3 using the symbols @jiska2342 provided above.

Did you add these symbols to the symbols.js, adapted bluetoothd.js to use these symbols, and compiled the harness script again? It seems to crash immediately at the connection allocation. Maybe the wrong address is called.

**Comment by SpiralBL0CK** [comment]
thx again @ttdennis spoke with xyn he and i work together and seems all working fine :) sorry for late answer tho.
